project:
  title: "mauricio-quarto-blog"
navbar: 
    right: 
        - about.qmd
        - icon: github
          href: https://github.com/maupagas
        - icon: twitter
          href: https://twitter.com/maupagas
format: 
  html: 
    theme: cerulean
    css: styles.css



